---
name: Validate scenarios

on: [push, pull_request]

jobs:
  katacoda:
    name: Validate Katacoda scenarios
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Katacoda CLI
        shell: sh
        run: sudo npm i katacoda-cli --global

      - name: Validate Katacoda scenarios
        shell: sh
        run: katacoda validate:all --repo ${{ github.workspace }}
